From 7823379f8690e4ffe8a1197c5c4716d9cb3a6bd3 Mon Sep 17 00:00:00 2001
From: xingzhou <xingzhou@cn.ibm.com>
Date: Wed, 10 Jul 2013 04:00:46 -0400
Subject: [PATCH] Ceilometer using external endpoint url for nova

Shall use adminURL instead

Change-Id: I63687d2ead63f6c0f899a9458de895af2f2e7efc
Fixes: Bug 1179560
---
 ceilometer/nova_client.py |    3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/ceilometer/nova_client.py b/ceilometer/nova_client.py
index d43b98f..b85328e 100644
--- a/ceilometer/nova_client.py
+++ b/ceilometer/nova_client.py
@@ -51,7 +51,8 @@ class Client(object):
             api_key=cfg.CONF.service_credentials.os_password,
             project_id=tenant,
             auth_url=cfg.CONF.service_credentials.os_auth_url,
-            no_cache=True)
+            no_cache=True,
+            endpoint_type='adminURL')
 
     def _with_flavor_and_image(self, instances):
         flavor_attrs = ['name', 'vcpus', 'ram', 'disk']
-- 
1.7.9.5

